// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewaetndthowtdjpxvsvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3YWV0bmR0aG93dGRqcHh2c3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMzk2NzcsImV4cCI6MjA3MDcxNTY3N30.v55_ym2C3YWExYl1HlxLyQDBj0w-_swbnuTHEnTc3hA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});